name: Build Linux ARMv7

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0

      - name: Build
        uses: uraimo/run-on-arch-action@v1.0.5
        with:
          architecture: armv7
          distribution: buster
          run: |
            apt-get update && apt-get install -y wget build-essential gcc python make zip
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            . "$NVM_DIR/nvm.sh"
            nvm install 12.2.0
            npm ci
            ln -s ./node_modules/sharp/build/Release/sharp.node sharp.node
            mkdir modules
            cp -r ./node_modules/sharp modules/
            npm run build-linux-armv7
            npm test
            zip -r armv7.zip .

      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./cli
          asset_name: cli-linux-armv7
          asset_content_type: application/x-executable; charset=binary

      - name: Upload Sharp
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./armv7.zip
          asset_name: armv7.zip
          asset_content_type: application/zip

